Bring in updates from NCO v2.0.15

diff --git a/ush/err_exit b/ush/err_exit
--- a/ush/err_exit
+++ b/ush/err_exit
@@ -2,70 +2,91 @@
 
 # SCRIPT NAME:  err_exit
 #
-# ABSTRACT:  This script is to be used when a fatal error or condition 
+# ABSTRACT:  This script is to be used when a fatal error or condition
 # has been reached and you want to terminate the job.
 #
 # USAGE:  To use this script one must export the following variables to the
 # script: jobid, SENDECF, pgm, pgmout, DATA. One can provide
 # a message for the logfile by passing it to the script as an argument.
 
-msg1=${@:-Job $jobid failed}
-if [ -n "$pgm" ]; then
-  msg1+=", ERROR IN $pgm"
+err=${err:-""}             # Return code from program
+pgm=${pgm:-""}             # Program name
+pgmout=${pgmout:-""}       # Program output file
+jobid=${jobid:-"UNKNOWN"}  # Job ID
+DATA=${DATA:-""}           # Working directory
+SENDECF=${SENDECF:-"NO"}   # Send message to ecflow
+ECF_NAME=${ECF_NAME:-""}   # Name of the ECF Job
+ECF_HOST=${ECF_HOST:-""}   # ecflow hostname
+ECF_JOBOUT=${ECF_JOBOUT:-""} # ecflow job output file
+JOBID=${JOBID:-$PBS_JOBID}   # Scheduler Job ID e.g. $PBS_JOBID, $SLURM_ID, etc
+KILLJOB=${KILLJOB:-qdel}     # Scheduler command to kill a job e.g. qdel, scancel, etc
+
+msg1=${*:-Job ${jobid} failed}
+if [[ -n "${pgm}" ]]; then
+    msg1+=", ERROR IN ${pgm}"
 fi
-if [ -n "$err" ]; then
-  msg1+=" RETURN CODE $err"
+if [[ -n "${err}" ]]; then
+    msg1+=" RETURN CODE ${err}"
 fi
 
 msg2="
 -------------------------------------------------------------
--- FATAL ERROR: $msg1
--- ABNORMAL EXIT at $(date) on $HOSTNAME
+-- FATAL ERROR: ${msg1}
+-- ABNORMAL EXIT at $(date) on ${HOSTNAME}
 -------------------------------------------------------------
 "
 
->&2 echo "$msg2"
+>&2 echo "${msg2}"
 
 # list loaded modules
 module list
 >&2 echo ""
 
->&2 echo "$msg1"
+>&2 echo "${msg1}"
 
 # list files in temporary working directory
-if [ -n "$DATA" ]; then
-  >&2 echo $DATA
-  >&2 ls -ltr $DATA
+if [[ -n "${DATA}" ]]; then
+    >&2 echo "${DATA}"
+    >&2 ls -ltr "${DATA}"
 else
-  >&2 echo "WARNING: DATA variable not defined"
+    >&2 echo "WARNING: DATA variable not defined"
 fi
 
 # save standard output
-if [ -n "$pgmout" ]; then
-  if [ -s errfile ]; then
-    echo "----- contents of errfile -----" >> $pgmout
-    cat errfile >> $pgmout
-  fi
-  >&2 cat $pgmout
-elif [ -s errfile ]; then
-  >&2 cat errfile
+if [[ -n "${pgmout}" ]]; then
+    if [[ -s errfile ]]; then
+        echo "----- contents of errfile -----" >> "${pgmout}"
+        cat errfile >> "${pgmout}"
+    fi
+    >&2 cat "${pgmout}"
+elif [[ -s errfile ]]; then
+    >&2 cat errfile
 fi
 
 # Write to ecflow log:
-if [ "$SENDECF" = "YES" ]; then
-  timeout 30 ecflow_client --msg "$ECF_NAME: $msg1"
-  timeout 30 ssh $ECF_HOST "echo \"$msg2\" >> ${ECF_JOBOUT:?}"
+if [[ "${SENDECF}" == "YES" ]]; then
+    timeout 30 ecflow_client --msg "${ECF_NAME}: ${msg1}"
+    if [[ -z "${ECF_JOBOUT}" || "${ECF_HOST}" == "" ]]; then
+        echo "FATAL ERROR Unable to write to ecflow server as either ECF_HOST or ECF_JOBOUT are undefined!!"
+    else
+        timeout 30 ssh "${ECF_HOST}" "echo \"${msg2}\" >> ${ECF_JOBOUT}"
+    fi
 fi
 
-# KILL THE JOB:
-if [ "$SENDECF" = "YES" ]; then
-  ecflow_client --kill=${ECF_NAME:?}
-fi
-
-if [ ! -z $PBS_JOBID ]; then
-  qdel $PBS_JOBID
-elif [ ! -z $SLURM_JOB_ID ]; then
-  scancel $SLURM_JOB_ID
-  echo "----- waiting for $SLURM_JOB_ID to be killed -----"
-  sleep 600
+# KILL THE JOB VIA ECFLOW:
+if [[ "${SENDECF}" == "YES" ]]; then
+    if [[ -z "${ECF_NAME}" ]]; then
+        echo "FATAL ERROR Unable to kill ecflow job as ECF_NAME variable is not set!!"
+    else
+        echo "Killing the job via ecflow kill"
+        ecflow_client --kill="${ECF_NAME}"
+    fi
+# KILL THE JOB VIA JOB SCHEDULER COMMAND:
+elif [[ -n "${KILLJOB}" && -n "${JOBID}" ]]; then
+    echo "Killing the job via ${KILLJOB}"
+    ${KILLJOB} ${JOBID}
+else
+    echo "Could not find a scheduler command or job ID to kill the current job"
+    echo "KILLJOB = ${KILLJOB}"
+    echo "JOBID   = ${JOBID}"
 fi
